[package]
name = "download_books"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "download_books"
path = "download_books.rs"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }